name: Main
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
    - master
  schedule:
    - cron:  0 0 * * *

jobs:
  build:
    name: Docker
    strategy:
      matrix:
        php_version: 
        - '7.1'
        - '7.2'
        - '7.3'
        - '7.4-rc'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      run: docker build --build-arg VERSION=${{ matrix.php_version }} -t nauxliu/php-ci-image:${{ matrix.php_version }} .
    - name: Login
      run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
    - name: Publish DockerHub
      run: docker push nauxliu/php-ci-image:${{ matrix.php_version }}
    - name: Publish GitHub
      run: |
        docker tag nauxliu/php-ci-image:${{ matrix.php_version }} docker.pkg.github.com/nauxliu/php-ci-image:${{ matrix.php_version }} 
        docker push docker.pkg.github.com/nauxliu/php-ci-image:${{ matrix.php_version }} 
